// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ItNpwXWgZwGkKxFK9b149i_h6n-HR1w',
    appId: '1:1044680486924:web:d4967b062592cb58a53e29',
    messagingSenderId: '1044680486924',
    projectId: 'words-power-d8330',
    authDomain: 'words-power-d8330.firebaseapp.com',
    storageBucket: 'words-power-d8330.appspot.com',
    measurementId: 'G-BK728L369M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-lkk5CCfhUrY5Q7EwkQvfeiqAkZYCag',
    appId: '1:1044680486924:android:9610be8345a30ebca53e29',
    messagingSenderId: '1044680486924',
    projectId: 'words-power-d8330',
    storageBucket: 'words-power-d8330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPPVsVq5RG0GvwuQvrpTkf6kvzxFKP18',
    appId: '1:1044680486924:ios:173b07bf0812215da53e29',
    messagingSenderId: '1044680486924',
    projectId: 'words-power-d8330',
    storageBucket: 'words-power-d8330.appspot.com',
    iosClientId: '1044680486924-vbl2813asqd1fjt543mp8op9oklu5gab.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordsPower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPPVsVq5RG0GvwuQvrpTkf6kvzxFKP18',
    appId: '1:1044680486924:ios:173b07bf0812215da53e29',
    messagingSenderId: '1044680486924',
    projectId: 'words-power-d8330',
    storageBucket: 'words-power-d8330.appspot.com',
    iosClientId: '1044680486924-vbl2813asqd1fjt543mp8op9oklu5gab.apps.googleusercontent.com',
    iosBundleId: 'com.example.wordsPower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5ItNpwXWgZwGkKxFK9b149i_h6n-HR1w',
    appId: '1:1044680486924:web:2c87dafa7d1adc35a53e29',
    messagingSenderId: '1044680486924',
    projectId: 'words-power-d8330',
    authDomain: 'words-power-d8330.firebaseapp.com',
    storageBucket: 'words-power-d8330.appspot.com',
    measurementId: 'G-VQ5JWNMP5S',
  );

}